### ISSUE TITLE
Server fails to stop gracefully

### ISSUE THREAD

**Issue by rjbprime** [GeekbeeGER/WindowsGSM.CoreKeeper#3]
Hi @GeekbeeGER,

When clicking stop in the WindowsGSM window for this server, the notification window panel says

```
Action: Stopped
Server: Stopped
[Notice] Server fail to stop gracefully
```

Options enabled for the panel above that are 

```
Process Priority: High
Embed Console: Yes
Update on Start: Yes
Backup on Start: Yes
Auto Update: Yes
```

All other options in that panel are the defaults. The WindowsGSM.cfg panel has had its Server Maxplayer changed from 100 to 10.

What can be done to gracefully shut the server down? I am hesitant to run this plugin for the moment, when I have not just myself but others playing on the server.

Kind regards.

**Comment by GeekbeeGER** [comment]
This is normal as the server is not shutting down as stated in the console "Press q to quit, DON'T close the window or the server process will just keep running".

**Comment by rjbprime** [comment]
Fair enough. When wanting to stop the server with this plugin, does one type q in the console and hit send? Or is there an option to open a console that allows this?

**Comment by GeekbeeGER** [comment]
No, if you type q in the console and send it, the server won't be caught,

**Comment by GeekbeeGER** [comment]
@rjbprime 
Stop server function now Fixxed
